#!/usr/bin/env python3
"""Build rsod-decode.pyzw — a standalone zipapp for the CLI analyzer.

Bundles the rsod_decode package plus its pure-Python dependencies
(pyelftools, cxxfilt, pefile, capstone) into a single executable zip.
Entry point is rsod_decode.cli:main.

ARCHITECTURE-SPECIFIC. capstone ships a native `libcapstone.so` that
is loaded via ctypes (not Python's zipimport), so the resulting pyzw
only runs on the same OS + CPU as the build host. On Linux x86_64
in this tree, that means the pyzw runs on Linux x86_64 only.

Packages that need real filesystem access (ctypes, __file__-relative
resource lookups) are listed in NATIVE_PACKAGES and get extracted to
~/.cache/rsod-decode/libs/<hash>/ on first run by the bootstrap
__main__.py. Pure-Python packages stay inside the zip and load via
zipimport.

What we do NOT bundle:

  - Flask / werkzeug / flask-sock / simple-websocket — the web UI's
    entry point (rsod-debug) stays an editable install, not a pyzw.
  - LLDB Python bindings — C extension tied to a specific LLVM
    version. The existing lldb_loader.py shim searches system paths
    at runtime and returns None gracefully when absent; that behavior
    works fine from inside a zipapp.
  - gdb_backend.py / gdb_bridge.py / pygdbmi — web-only, not reached
    by the CLI's transitive import closure.
  - tests/, tests/fixtures/, frontend/, .venv/, .git/
  - .dist-info metadata dirs
"""
from __future__ import annotations

import importlib.util
import shutil
import sys
import zipapp
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
STAGING = ROOT / "build" / "pyzw-staging"
OUT = ROOT / "rsod-decode.pyzw"

# Pure-Python third-party packages copied into the zip verbatim.
PURE_PACKAGES = ["elftools", "cxxfilt", "pefile"]

# Packages that contain native code (ctypes-loaded .so files or
# __file__-relative resources). These are bundled in the zip but the
# bootstrap __main__.py extracts them to a cache dir on first run
# because zipimport can't serve ctypes.CDLL.
NATIVE_PACKAGES = ["capstone"]

IGNORE = shutil.ignore_patterns(
    "__pycache__", "*.pyc", "*.pyo", "*.pyi",
    "tests", "test", "*.dist-info", "*.egg-info",
)


def _copy_package(name: str, dest_parent: Path) -> None:
    spec = importlib.util.find_spec(name)
    if spec is None or spec.origin is None:
        raise RuntimeError(f"cannot locate package {name!r} in current env")
    if spec.submodule_search_locations:
        src = Path(spec.origin).parent
        shutil.copytree(src, dest_parent / src.name,
                        dirs_exist_ok=True, ignore=IGNORE)
    else:
        shutil.copy2(spec.origin, dest_parent / Path(spec.origin).name)


# The bootstrap __main__.py lives at the root of the zip. Written as a
# string so we can template NATIVE_PACKAGES into it at build time.
_BOOTSTRAP_TEMPLATE = '''\
# Auto-generated by build_pyz.py — do not edit.
# Extracts bundled native packages to a cache dir, then delegates to
# rsod_decode.cli:main.
from __future__ import annotations

import hashlib
import sys
import zipfile
from pathlib import Path

NATIVE_PACKAGES = {native_packages!r}


def _extract_native_packages() -> None:
    """Extract ctypes-backed packages out of the zipapp into a cache dir.

    capstone (and any other package in NATIVE_PACKAGES) loads a shared
    library via ctypes.CDLL using a __file__-relative path, which
    fails under zipimport. Extracting the whole package to a real
    filesystem location and prepending that dir to sys.path lets the
    standard import machinery find it first.
    """
    zpath = Path(sys.argv[0]).resolve()
    if not zpath.exists() or not zipfile.is_zipfile(zpath):
        return  # running from staging dir, not a zipapp — dev mode
    digest = hashlib.sha256()
    with zpath.open("rb") as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            digest.update(chunk)
    cache = Path.home() / ".cache" / "rsod-decode" / "libs" / digest.hexdigest()[:16]
    marker = cache / ".extracted"
    if not marker.exists():
        cache.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(zpath) as zf:
            for name in zf.namelist():
                top = name.split("/", 1)[0]
                if top in NATIVE_PACKAGES:
                    zf.extract(name, cache)
        marker.touch()
    sys.path.insert(0, str(cache))


_extract_native_packages()

from rsod_decode.cli import main  # noqa: E402

raise SystemExit(main())
'''


def main() -> None:
    if STAGING.exists():
        shutil.rmtree(STAGING)
    STAGING.mkdir(parents=True)

    # Application code.
    shutil.copytree(ROOT / "src" / "rsod_decode", STAGING / "rsod_decode",
                    ignore=IGNORE)

    # Third-party deps.
    for pkg in PURE_PACKAGES + NATIVE_PACKAGES:
        _copy_package(pkg, STAGING)

    # Bootstrap entry point.
    bootstrap = _BOOTSTRAP_TEMPLATE.format(native_packages=NATIVE_PACKAGES)
    (STAGING / "__main__.py").write_text(bootstrap, encoding="utf-8")

    if OUT.exists():
        OUT.unlink()
    zipapp.create_archive(
        STAGING, target=OUT,
        interpreter="/usr/bin/env python3",
        compressed=True,
    )
    OUT.chmod(0o755)
    size_mb = OUT.stat().st_size / (1024 * 1024)
    print(f"built {OUT.name} ({size_mb:.1f} MB) from staging {STAGING}")


if __name__ == "__main__":
    main()
